/* LOG IN */
export const AUTH_LOG_IN_DO = "AUTH_LOG_IN_DO";
export const AUTH_LOG_IN_SUCCESS = "AUTH_LOG_IN_SUCCESS";
export const AUTH_LOG_IN_FAILURE = "AUTH_LOG_IN_FAILURE";

/* SIGN UP */
export const AUTH_SIGN_UP_DO = "AUTH_SIGN_UP_DO";
export const AUTH_SIGN_UP_SUCCESS = "AUTH_SIGN_UP_SUCCESS";
export const AUTH_SIGN_UP_FAILURE = "AUTH_SIGN_UP_FAILURE";

/* VERIFY */
export const AUTH_VERIFY_DO = "AUTH_VERIFY_DO";
export const AUTH_VERIFY_SUCCESS = "AUTH_VERIFY_SUCCESS";
export const AUTH_VERIFY_FAILURE = "AUTH_VERIFY_FAILURE";

/* REFRESH TOKEN */
export const AUTH_REFRESH_TOKEN_DO = "AUTH_REFRESH_TOKEN_DO";

/* GOOGLE VERIFY */
export const AUTH_G_VERIFY_DO = "AUTH_G_VERIFY_DO";
export const AUTH_G_VERIFY_SUCCESS = "AUTH_G_VERIFY_SUCCESS";
export const AUTH_G_VERIFY_FAILURE = "AUTH_G_VERIFY_FAILURE";

/* LOG OUT */
export const AUTH_LOG_OUT = "AUTH_LOG_OUT";
